application: eventflairs
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:  
- url: /js
  static_dir: static/js
  mime_type: application/javascript

- url: /css
  static_dir: static/css
  mime_type: text/css

- url: /images
  static_dir: static/images
  mime_type: image/jpeg

- url: /static
  static_dir: static
 
- url: /.*
  static_files: index.html
  upload: index\.html

libraries:
- name: webapp2
  version: "2.5.2"
